name: First Workflow

on: 
  push:
    paths:
      - '.github/workflows/hello.yml'
  pull_request:
    

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello, Github Actions..!!"